Repository DoZoltan/TeamProject-CoolJobAPI, pull requests merged in 2021-04, with the labels that each got.

#3 Update tests to fit for new job id
  CoolJobAPI/Controllers/FavoritesController.cs
  CoolJobAPI/Controllers/JobsController.cs
  CoolJobAPI/Migrations/20210414095405_InitialMigration.Designer.cs
  CoolJobAPI/Migrations/20210414095405_InitialMigration.cs
  CoolJobAPI/Migrations/JobContextModelSnapshot.cs
  CoolJobAPI/Models/FavoriteRepository.cs
  CoolJobAPI/Models/IFavoriteRepository.cs
  CoolJobAPI/Models/IJobRepository.cs
  CoolJobAPI/Models/Job.cs
  CoolJobAPI/Models/JobRepository.cs
  CoolJobAPI/Models/User.cs
  CoolJobAPI/wwwroot/data/data.json
  README.md
Labels: invalid

#4 Changed unit tests to fit to the int job IDs
  CoolJobAPI.UnitTests/ControllersTest/FavoritesControllerTest.cs
  CoolJobAPI.UnitTests/ControllersTest/JobsControllerTest.cs
  CoolJobAPI.UnitTests/ReositoryTests/FavoriteRepositiryTest.cs
  CoolJobAPI.UnitTests/ReositoryTests/JobRepositoryTest.cs
  CoolJobAPI/Controllers/FavoritesController.cs
  CoolJobAPI/Controllers/JobsController.cs
  CoolJobAPI/Migrations/20210414095405_InitialMigration.Designer.cs
  CoolJobAPI/Migrations/20210414095405_InitialMigration.cs
  CoolJobAPI/Migrations/JobContextModelSnapshot.cs
  CoolJobAPI/Models/FavoriteRepository.cs
  CoolJobAPI/Models/IFavoriteRepository.cs
  CoolJobAPI/Models/IJobRepository.cs
  CoolJobAPI/Models/Job.cs
  CoolJobAPI/Models/JobRepository.cs
  CoolJobAPI/Models/User.cs
  CoolJobAPI/wwwroot/data/data.json
Labels: bug

#5 Adminkey for reload db
  CoolJobAPI/Controllers/JobsController.cs
  CoolJobAPI/Models/IJobRepository.cs
  CoolJobAPI/Models/JobRepository.cs
  CoolJobAPI/Properties/launchSettings.json
  CoolJobAPI/wwwroot/data/admin.json
Labels: bug, enhancement
