Repository DoZoltan/TeamProject-CoolJobAPI, pull requests merged in 2021-05, with the labels that each got.

#6 Add new job by user
  CoolJobAPI/Controllers/JobsController.cs
  CoolJobAPI/Models/IJobRepository.cs
  CoolJobAPI/Models/JobRepository.cs
  CoolJobAPI/wwwroot/data/cities.json
Labels: bug

#7 Send status code
  CoolJobAPI/Controllers/FavoritesController.cs
  CoolJobAPI/Controllers/FilterController.cs
  CoolJobAPI/Controllers/JobsController.cs
  CoolJobAPI/Controllers/JobsPageController.cs
  CoolJobAPI/Controllers/UsersController.cs
  CoolJobAPI/Models/FavoriteRepository.cs
  CoolJobAPI/Models/IFavoriteRepository.cs
  CoolJobAPI/Models/IJobRepository.cs
  CoolJobAPI/Models/JobContext.cs
  CoolJobAPI/Models/JobRepository.cs
  CoolJobAPI/Startup.cs
Labels: bug, enhancement

#8 Async methods
  CoolJobAPI/Controllers/FavoritesController.cs
  CoolJobAPI/Controllers/JobsController.cs
  CoolJobAPI/Controllers/JobsPageController.cs
  CoolJobAPI/Interfaces/IFavoriteRepository.cs
  CoolJobAPI/Interfaces/IJobRepository.cs
  CoolJobAPI/Interfaces/IUserRepository.cs
  CoolJobAPI/Models/IFavoriteRepository.cs
  CoolJobAPI/Models/IJobRepository.cs
  CoolJobAPI/Repositories/FavoriteRepository.cs
  CoolJobAPI/Repositories/JobRepository.cs
  CoolJobAPI/Repositories/UserRepository.cs
Labels: enhancement

#10 Reload database
  CoolJobAPI/Controllers/JobsController.cs
  CoolJobAPI/Interfaces/IJobRepository.cs
  CoolJobAPI/Repositories/JobRepository.cs
Labels: bug, enhancement
